version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    environment:
        GMAIL_USERNAME: asd
        GMAIL_PASSWORD: asd
        omniauth.auth: asd
        FACEBOOK_APP_ID:
        FACEBOOK_APP_SECRET:
        TWITTER_APP_ID:
        TWITTER_APP_SECRET:
        SECRET_KEY_BASE: 
        TOKEN_MAI_GET:
        ######### test
        RAILS_ENV: production
        production: true
    depends_on:
      - db