require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TransactionDetailsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # TransactionDetail. As you add validations to TransactionDetail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransactionDetailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all transaction_details as @transaction_details" do
      transaction_detail = TransactionDetail.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:transaction_details)).to eq([transaction_detail])
    end
  end

  describe "GET show" do
    it "assigns the requested transaction_detail as @transaction_detail" do
      transaction_detail = TransactionDetail.create! valid_attributes
      get :show, {:id => transaction_detail.to_param}, valid_session
      expect(assigns(:transaction_detail)).to eq(transaction_detail)
    end
  end

  describe "GET new" do
    it "assigns a new transaction_detail as @transaction_detail" do
      get :new, {}, valid_session
      expect(assigns(:transaction_detail)).to be_a_new(TransactionDetail)
    end
  end

  describe "GET edit" do
    it "assigns the requested transaction_detail as @transaction_detail" do
      transaction_detail = TransactionDetail.create! valid_attributes
      get :edit, {:id => transaction_detail.to_param}, valid_session
      expect(assigns(:transaction_detail)).to eq(transaction_detail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransactionDetail" do
        expect {
          post :create, {:transaction_detail => valid_attributes}, valid_session
        }.to change(TransactionDetail, :count).by(1)
      end

      it "assigns a newly created transaction_detail as @transaction_detail" do
        post :create, {:transaction_detail => valid_attributes}, valid_session
        expect(assigns(:transaction_detail)).to be_a(TransactionDetail)
        expect(assigns(:transaction_detail)).to be_persisted
      end

      it "redirects to the created transaction_detail" do
        post :create, {:transaction_detail => valid_attributes}, valid_session
        expect(response).to redirect_to(TransactionDetail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved transaction_detail as @transaction_detail" do
        post :create, {:transaction_detail => invalid_attributes}, valid_session
        expect(assigns(:transaction_detail)).to be_a_new(TransactionDetail)
      end

      it "re-renders the 'new' template" do
        post :create, {:transaction_detail => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested transaction_detail" do
        transaction_detail = TransactionDetail.create! valid_attributes
        put :update, {:id => transaction_detail.to_param, :transaction_detail => new_attributes}, valid_session
        transaction_detail.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested transaction_detail as @transaction_detail" do
        transaction_detail = TransactionDetail.create! valid_attributes
        put :update, {:id => transaction_detail.to_param, :transaction_detail => valid_attributes}, valid_session
        expect(assigns(:transaction_detail)).to eq(transaction_detail)
      end

      it "redirects to the transaction_detail" do
        transaction_detail = TransactionDetail.create! valid_attributes
        put :update, {:id => transaction_detail.to_param, :transaction_detail => valid_attributes}, valid_session
        expect(response).to redirect_to(transaction_detail)
      end
    end

    describe "with invalid params" do
      it "assigns the transaction_detail as @transaction_detail" do
        transaction_detail = TransactionDetail.create! valid_attributes
        put :update, {:id => transaction_detail.to_param, :transaction_detail => invalid_attributes}, valid_session
        expect(assigns(:transaction_detail)).to eq(transaction_detail)
      end

      it "re-renders the 'edit' template" do
        transaction_detail = TransactionDetail.create! valid_attributes
        put :update, {:id => transaction_detail.to_param, :transaction_detail => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested transaction_detail" do
      transaction_detail = TransactionDetail.create! valid_attributes
      expect {
        delete :destroy, {:id => transaction_detail.to_param}, valid_session
      }.to change(TransactionDetail, :count).by(-1)
    end

    it "redirects to the transaction_details list" do
      transaction_detail = TransactionDetail.create! valid_attributes
      delete :destroy, {:id => transaction_detail.to_param}, valid_session
      expect(response).to redirect_to(transaction_details_url)
    end
  end

end
